- name: Remove an EN instance from AAP
  hosts: localhost

  environment:
    CONTROLLER_HOST: "{{ controller_hostname }}"
    CONTROLLER_OAUTH_TOKEN: "{{ controller_token }}"
    CONTROLLER_VERIFY_SSL: false

  vars_files:
    - secrets.yml

  tasks:
  - name: Create the ec2 machine cred using sdunnerh
    ansible.controller.credential:
      name: ec2 instance
      organization: Default
      state: present
      credential_type: Machine
      inputs:
        username: ec2-user
        ssh_key_data: "{{ lookup('file', '/home/runner/.aws/sdunnerh') }}"
        #ssh_key_data: "{{ ssh_key_for_ec2 }}"
    changed_when: false
