---
- name: Setup sdunne user on ec2 for EN deployment
  hosts: "{{ _hosts }}"
  become: true

  tasks:
    - name: Update rhel packages
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Add sdunne user
      ansible.builtin.user:
        name: sdunne
        state: present
        append: true
        groups: wheel

    - name: Create .ssh directory for sdunne user
      ansible.builtin.file:
        path: /home/sdunne/.ssh
        state: directory
        owner: sdunne
        group: sdunne
        mode: '0700' 

    - name: Copy authorized_keys from ec2-user
      ansible.builtin.copy:
        src: /home/ec2-user/.ssh/authorized_keys
        remote_src: true
        dest: /home/sdunne/.ssh/authorized_keys
        mode: '600'
        owner: sdunne
        group: sdunne

    - name: Fix wheel group in sudoers no password
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWORD: ALL 
