---
- name: Create a SNOW incident
  hosts: localhost

  vars_files:
    - secrets.yml

# uncomment section for testing with ansible-navigator
#  module_defaults:
#    servicenow.itsm.incident:
#      instance:
#        host: "{{ sn_host }}"
#        username: "{{ sn_user }}"
#        password: "{{ sn_password }}"

  tasks:
    - name: Create incident
      servicenow.itsm.incident:
        state: new
        caller: sebastian.dunne
        short_description: Test incident created with Ansible
        description: The service *service* stopped running.
  #      attachments:
  #        - path: path/to/attachment.txt
        impact: low
        urgency: low
      register: sn_response

    - name: Show incident creation details
      ansible.builtin.debug:
        var: sn_response.record

    - name: Change state to in_progress
      servicenow.itsm.incident:
        number: "{{ sn_response['record']['number'] }}"
        state: in_progress

    - name: Create variable for SNOW ticket number
      ansible.builtin.set_stats:
        data:
          sn_ticket_number: "{{ sn_response['record']['number'] }}"


