---
- name: Pull and show SNOW incident info
  hosts: localhost

  vars_files:
    - secrets.yml

#  module_defaults:
#    servicenow.itsm.incident:
#      instance:
#        host: "{{ sn_host }}"
#        username: "{{ sn_user }}"
#        password: "{{ sn_password }}"

  tasks:
    - name: Pull incident info
      servicenow.itsm.incident_info:
        number: "{{ ticket }}"
        #number: eventdata.number
        #number: "{{ sn_response['record']['number'] }}"
      register: result

    - name: Show incident info
      ansible.builtin.debug:
        var: result

