---
- name: EDA response to Splunk alert
  hosts: localhost
  become: true

  tasks:
    - name: Show eventdata var
      ansible.builtin.debug:
        var: eventdata

    - name: Send test email
      community.general.mail:
        host: smtp.gmail.com
        port: 587
        username: "{{ gmail_username }}"
        password: "{{ gmail_app_password }}"
        to: Sebastian Dunne <sdunne@redhat.com>
        subject: Ansible-report
        body: > The {{ eventdata.ansible_result.name }} configuration 
              of {{ eventdata.ansible_host }} has changed. Please ensure 
              the {{ eventdata.ansible_result.name }} is {{ eventdata.ansible_result.state }}.
      delegate_to: localhost
      check_mode: no

