---
- name: EDA response to Splunk alert
  hosts: localhost
  become: true

  tasks:
    - name: Show eventdata var
      ansible.builtin.debug:
        #var: eventdata.result.ansible_host
        var: eventdata

    - name: Send test email
      community.general.mail:
        host: smtp.gmail.com
        port: 587
        username: "{{ gmail_username }}"
        password: "{{ gmail_app_password }}"
        to: Sebastian Dunne <sdunne@redhat.com>
        subject: Ansible-report
        body: | 
              The configuration of {{ eventdata['result']['host'] }} has changed.  
              Please check the {{ eventdata['result']['unit'] }} service.
        # delegate_to: localhost

