- name: Listen for events on a webhook from ServiceNow
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5003

  rules:
    - name: Output ServiceNow Information
      condition: event.meta is defined
      action:
        run_job_template:
          name: "Show SNOW payload"
          organization: Default
          job_args:
            extra_vars:
              eventdata: "{{ event.payload }}"
              #_hosts: "{{ event.payload.result.host }}"
        #debug:
